DROP TABLE USERS_BANK
DROP TABLE ACCOUNTS_BANK

CREATE TABLE USERS_BANK (

 USER_ID NUMBER(10) PRIMARY KEY,
 FIRSTNAME VARCHAR(25) NOT NULL,
 LASTNAME VARCHAR(25) NOT NULL,
 USERNAME VARCHAR(25) UNIQUE NOT NULL,
 PASS_WORD VARCHAR(50) NOT NULL  

);

CREATE TABLE ACCOUNTS_BANK (
 
 OWNER_ACCOUNT NUMBER(10) NOT NULL,
 ACCOUNT_ID NUMBER(10) PRIMARY KEY,
 ACCOUNT_BALANCE NUMBER(15) NOT NULL,
 
  FOREIGN KEY (OWNER_ACCOUNT) REFERENCES USERS_BANK(USER_ID)
 
);

