CREATE USER quizzard
IDENTIFIED BY  M1ch1gan
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON USERS;

GRANT CONNECT TO quizzard;
GRANT CREATE SESSION TO quizzard;
GRANT RESOURCE TO quizzard;
GRANT CREATE TABLE TO quizzard;
GRANT CREATE VIEW TO quizzard;