server:
  port: 8080

spring:
  application:
    name: gateway-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: true

zuul:
  routes:
    flash-card-service:
      path: /flash-cards/*
      strip-prefix: true
      serviceId: flash-card-service