CREATE USER rbs_app
IDENTIFIED BY p4ssw0rd
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT CONNECT TO rbs_app;
GRANT RESOURCE TO rbs_app;
GRANT CREATE SESSION TO rbs_app;
GRANT CREATE TABLE TO rbs_app;
GRANT CREATE VIEW TO rbs_app;