--2.1 JC
SELECT * FROM Employee;
SELECT * FROM Employee WHERE lastname= 'King';
SELECT * FROM Employee WHERE firstname= 'Andrew' AND REPORTSTO IS NULL;
--2.2 JC
SELECT * FROM Album ORDER BY TITLE DESC;
SELECT firstname FROM Customer ORDER BY firstname ASC;
--2.3 JC
INSERT INTO Genre (GENREID, NAME) VALUES (26,'Gunner');
INSERT INTO Genre (GENREID, NAME) VALUES (27,'Kannon');

INSERT INTO Employee (EMPLOYEEID, LASTNAME,FIRSTNAME, TITLE) VALUES (12,'CARTER', 'GUNNER','TOP DOG','07-SEPT-12');
INSERT INTO Employee (EMPLOYEEID, LASTNAME,FIRSTNAME, TITLE) VALUES (11,'CAR', 'KAN','TOP DOG','12-SEPT-15');

INSERT INTO Customer (CUSTOMERID,FIRSTNAME,LASTNAME, EMAIL) VALUES (60,'Jared','Cutter','JAREDC@YAHOO.COM');
INSERT INTO 
Customer (CUSTOMERID,FIRSTNAME,LASTNAME, EMAIL) VALUES (61,'Jerry','Hutter', 'JERRYHUTER@YAHOO.COM');
--2.4 JC
UPDATE Customer 
SET FIRSTNAME = 'ROBERT', LASTNAME= 'WALTER'
WHERE FIRSTNAME = 'Aaron' AND LASTNAME= 'Mitchell';

UPDATE Artist 
SET NAME='CCR' 
WHERE NAME='Creedence Clearwater Revival';
--2.5 JC

SELECT * 
FROM Invoice 
WHERE billingaddress LIKE 'T%';
--2.6 JC
SELECT * FROM Invoice WHERE INVOICEID BETWEEN 15 AND 50;

SELECT * FROM Employee WHERE HIREDATE BETWEEN '01-JUNE-2003' AND '01-MAR-2004';

--2.7 JC
ALTER TABLE InvoiceLine DROP CONSTRAINT FK_INVOICELINEINVOICEID;
ALTER TABLE InvoiceLine ADD CONSTRAINT FK_InvoicLineInvoiceId   FOREIGN KEY (CustomerId) REFERENCES Customer (CustomerId)
ON DELETE CASCADE; 

ALTER TABLE InvoiceLine DROP CONSTRAINT FK_INVOICELINEINVOICEID;
ALTER TABLE InvoiceLine  ADD CONSTRAINT FK_InvoiceLineInvoiceId FOREIGN KEY (InvoiceId) REFERENCES Invoice (InvoiceId)ON DELETE CASCADE;
    
DELETE FROM Customer WHERE FirstName='Robert' AND LastName='Walter';

--3.1 JC 
