INSERT INTO user_role VALUES (0, 'ADMIN');
INSERT INTO user_role VALUES (0, 'DEV');
INSERT INTO user_role VALUES (0, 'BASIC_USER');
INSERT INTO user_role VALUES (0, 'PREMIUM_USER');
INSERT INTO user_role VALUES (0, 'LOCKED');

INSERT INTO app_user VALUES (0, 'wsingleton', 'revature', 'Wezley', 'Singleton', 1);
INSERT INTO app_user VALUES (0, 'rconnell', 'rolltide', 'Robert', 'Connell', 1);
INSERT INTO app_user VALUES (0, 'skelsey', 'revasteve', 'Steven', 'Kelsey', 2);
INSERT INTO app_user VALUES (0, 'mknighten', 'knifehand', 'Jason', 'Knighten', 3);
INSERT INTO app_user VALUES (0, 'bkruppa', 'revature', 'Blake', 'Kruppa', 4);
INSERT INTO app_user VALUES (0, 'trolluser', 'banned', 'Eric', 'Cartman', 5);

INSERT INTO category VALUES (0, 'Core Java');
INSERT INTO category VALUES (0, 'Java Threads');
INSERT INTO category VALUES (0, 'Java Reflection');
INSERT INTO category VALUES (0, 'Java Collections');
INSERT INTO category VALUES (0, 'Java Streams');
INSERT INTO category VALUES (0, 'Oracle SQL');
INSERT INTO category VALUES (0, 'PostgreSQL');
INSERT INTO category VALUES (0, 'Oracle PL/SQL');
INSERT INTO category VALUES (0, 'Postgre PL/pgSQL');
INSERT INTO category VALUES (0, 'JDBC');
INSERT INTO category VALUES (0, 'HTML');
INSERT INTO category VALUES (0, 'CSS');
INSERT INTO category VALUES (0, 'Core JavaScript');
INSERT INTO category VALUES (0, 'JavaScript DOM Manipulation');
INSERT INTO category VALUES (0, 'AJAX');
INSERT INTO category VALUES (0, 'Fetch API');
INSERT INTO category VALUES (0, 'Axios');
INSERT INTO category VALUES (0, 'Java Servlets');
INSERT INTO category VALUES (0, 'TypeScript');
INSERT INTO category VALUES (0, 'Node.js');
INSERT INTO category VALUES (0, 'Angular');
INSERT INTO category VALUES (0, 'React');
INSERT INTO category VALUES (0, 'Redux');
INSERT INTO category VALUES (0, 'Express');
INSERT INTO category VALUES (0, 'AWS Cloud');
INSERT INTO category VALUES (0, 'MS Azure Cloud');
INSERT INTO category VALUES (0, 'DevOps Principles');
INSERT INTO category VALUES (0, 'Jenkins');
INSERT INTO category VALUES (0, 'Containerization');
INSERT INTO category VALUES (0, 'Container Orchestration');
INSERT INTO category VALUES (0, 'Hibernate');
INSERT INTO category VALUES (0, 'Core Spring Framework');
INSERT INTO category VALUES (0, 'Spring Boot');
INSERT INTO category VALUES (0, 'Spring Data');
INSERT INTO category VALUES (0, 'Service Oriented Architecture');
INSERT INTO category VALUES (0, 'REST Web Services');
INSERT INTO category VALUES (0, 'SOAP Web Services');
INSERT INTO category VALUES (0, 'Microservice Architecture');
INSERT INTO category VALUES (0, 'Messaging Queues');

INSERT INTO flashcard VALUES (0, 'Dummy Core Java Question 1', 'Dummy Answer', 1);
INSERT INTO flashcard VALUES (0, 'Dummy Core Java Question 2', 'Dummy Answer', 1);
INSERT INTO flashcard VALUES (0, 'Dummy Core Java Question 3', 'Dummy Answer', 1);
INSERT INTO flashcard VALUES (0, 'Dummy Java Threads Question 1', 'Dummy Answer', 2);
INSERT INTO flashcard VALUES (0, 'Dummy Oracle SQL Question 1', 'Dummy Answer', 6);
INSERT INTO flashcard VALUES (0, 'Dummy Oracle SQL Question 2', 'Dummy Answer', 6);
INSERT INTO flashcard VALUES (0, 'Dummy Core JavaScript Question 1', 'Dummy Answer', 13);
INSERT INTO flashcard VALUES (0, 'Dummy Core JavaScript Question 2', 'Dummy Answer', 13);
INSERT INTO flashcard VALUES (0, 'Dummy Core JavaScript Question 3', 'Dummy Answer', 13);
INSERT INTO flashcard VALUES (0, 'Dummy Core JavaScript Question 4', 'Dummy Answer', 13);
INSERT INTO flashcard VALUES (0, 'Dummy Angular Question 1', 'Dummy Answer', 21);
INSERT INTO flashcard VALUES (0, 'Dummy React Question 1', 'Dummy Answer', 22);
INSERT INTO flashcard VALUES (0, 'Dummy React Question 2', 'Dummy Answer', 22);
INSERT INTO flashcard VALUES (0, 'Dummy DevOps Principles Question 1', 'Dummy Answer', 27);
INSERT INTO flashcard VALUES (0, 'Dummy Containerization Question 1', 'Dummy Answer', 29);
INSERT INTO flashcard VALUES (0, 'Dummy Containerization Question 2', 'Dummy Answer', 29);
INSERT INTO flashcard VALUES (0, 'Dummy Hibernate Question 1', 'Dummy Answer', 31);
INSERT INTO flashcard VALUES (0, 'Dummy Hibernate Question 2', 'Dummy Answer', 31);
INSERT INTO flashcard VALUES (0, 'Dummy Core Spring Question 1', 'Dummy Answer', 32);
INSERT INTO flashcard VALUES (0, 'Dummy Core Spring Question 2', 'Dummy Answer', 32);
INSERT INTO flashcard VALUES (0, 'Dummy Spring Boot Question 1', 'Dummy Answer', 33);
INSERT INTO flashcard VALUES (0, 'Dummy Spring Boot Question 2', 'Dummy Answer', 33);
INSERT INTO flashcard VALUES (0, 'Dummy Microservice Architecture Question 1', 'Dummy Answer', 38);
INSERT INTO flashcard VALUES (0, 'Dummy Microservice Architecture Question 2', 'Dummy Answer', 38);

INSERT INTO study_set VALUES (0, 'Core Java Study Set', 4);
INSERT INTO study_set VALUES (0, 'Spring Study Set', 4);
INSERT INTO study_set VALUES (0, 'Core JavaScript Study Set', 5);
INSERT INTO study_set VALUES (0, 'React Study Set', 5);
INSERT INTO study_set VALUES (0, 'DevOps Study Set', 5);

INSERT INTO study_set_card VALUES (1, 1);
INSERT INTO study_set_card VALUES (1, 2);
INSERT INTO study_set_card VALUES (1, 3);
INSERT INTO study_set_card VALUES (2, 19);
INSERT INTO study_set_card VALUES (2, 20);
INSERT INTO study_set_card VALUES (2, 21);
INSERT INTO study_set_card VALUES (2, 22);
INSERT INTO study_set_card VALUES (3, 7);
INSERT INTO study_set_card VALUES (3, 8);
INSERT INTO study_set_card VALUES (3, 9);
INSERT INTO study_set_card VALUES (3, 10);
INSERT INTO study_set_card VALUES (4, 12);
INSERT INTO study_set_card VALUES (4, 13);
INSERT INTO study_set_card VALUES (5, 14);
INSERT INTO study_set_card VALUES (5, 15);
INSERT INTO study_set_card VALUES (5, 16);

COMMIT;
