server:
  port: 10001

spring:
  application:
    name: flash-card-service

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: false
    register-with-eureka: true
