server: 
  port: 8080
  
spring:  datasource:    platform: h2
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:    console:      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false 
  jpa:    database-platform: org.hibernate.dialect.H2Dialect
    properties:      hibernate:
        show-sql: true
        format-sql: true
        use-sql-comments: true
        ddl-auto: create